#import "GameModeResourceReq.h"
#import "Resource.h"

@implementation GameModeResourceReq

static NSArray *intro;
static NSArray *menu;
static NSArray *game;

+(void)initialize {
	intro = @[
		TEX_INTRO_ANIM_SS,
		TEX_BG_SKY,
		TEX_BG_STARS,
		TEX_BG_MOON,
		TEX_BG_LAYER_3,
		TEX_BG_LAYER_1,
		TEX_CLOUD_SS,
		TEX_NMENU_LOGO
	];
	
	menu = @[
		TEX_NMENU_ITEMS,
		TEX_UI_INGAMEUI_SS,
		TEX_ITEM_SS,
		TEX_NMENU_LOGO,
		TEX_BIRD_SS,
		TEX_NMENU_LEVELSELOBJ,
		TEX_FREERUNSTARTICONS,
		TEX_BG_SKY,
		TEX_BG_STARS,
		TEX_CLOUD_SS,
		TEX_BG_LAYER_3,
		TEX_NMENU_BG,
		TEX_BG_SUN,
		TEX_BG_MOON,
		TEX_PARTICLES,
		TEX_DOG_RUN_1,
		TEX_DOG_RUN_2,
		TEX_DOG_RUN_3,
		TEX_DOG_RUN_4,
		TEX_DOG_RUN_5,
		TEX_DOG_RUN_6,
		TEX_DOG_RUN_7,
		TEX_DOG_SHADOW,
		TEX_NMENU_DOGHOUSEMASK
	];
	
	game = @[
		TEX_SWEATANIM_SS,
		TEX_DASHJUMPPARTICLES_SS,
		TEX_DOG_RUN_1,
		TEX_DOG_RUN_2,
		TEX_DOG_RUN_3,
		TEX_DOG_RUN_4,
		TEX_DOG_RUN_5,
		TEX_DOG_RUN_6,
		TEX_DOG_RUN_7,
		TEX_DOG_SPLASH,
		TEX_DOG_ARMORED,
		TEX_DOG_SHADOW,
		TEX_BG_SKY,
		TEX_BG_STARS,
		TEX_BG_SUN,
		TEX_BG_MOON,
		TEX_BG_LAYER_3,
		TEX_CLOUD_SS,
		TEX_BG_LAYER_1,
		TEX_LAB_BG,
		TEX_LAB_BG_LAYER,
		TEX_BG2_SKY,
		TEX_BG2_CLOUDS_SS,
		TEX_BG2_BACKHILLS,
		TEX_BG2_FRONTHILLS,
		TEX_BG2_WATER,
		TEX_BG2_FRONTISLANDS_1,
		TEX_BG2_FRONTISLANDS_0,
		TEX_LAB2_WINDOWWALL,
		TEX_LAB2_WATER_BACK,
		TEX_ENEMY_SUBBOSS,
		TEX_LAB2_TANKER_BACK,
		TEX_LAB2_TANKER_FRONT,
		TEX_LAB2_DOCKS,
		TEX_LAB2_WATER_FRONT,
		TEX_BG3_SKY,
		TEX_BG3_BACKMOUNTAINS,
		TEX_BG3_CASTLE,
		TEX_BG3_BACKHILLS,
		TEX_BG3_FRONTHILLS,
		TEX_UI_INGAMEUI_SS,
		TEX_NMENU_ITEMS,
		TEX_NMENU_LEVELSELOBJ,
		TEX_ITEM_SS,
		TEX_BLANK,
		TEX_PARTICLES,
		TEX_GROUND_TEX_1,
		TEX_GROUND_CORNER_TEX_1,
		TEX_GROUND_TOP_1,
		TEX_GROUND_DETAILS,
		TEX_BRIDGE_EDGE,
		TEX_BRIDGE_SECTION,
		TEX_WATER,
		TEX_FISH_SS,
		TEX_CHECKPOINT_1,
		TEX_CHECKPOINT_2,
		TEX_BIRD_SS,
		TEX_SPEEDUP,
		TEX_ISLAND_BORDER,
		TEX_TOP_EDGE,
		TEX_TUTORIAL_ANIM_1,
		TEX_TUTORIAL_ANIM_2,
		TEX_TUTORIAL_OBJ
	];
}

+(NSArray*)tex_keys_intro {
	return intro;
}

+(NSArray*)tex_keys_menu {
	return menu;
}

+(NSArray*)tex_keys_game {
	return game;
}

@end
